name: Release

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - "sdk-v*"
      - "proxy-v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Determine package
        id: package
        run: |
          if [[ "${{ github.ref }}" == refs/tags/sdk-v* ]]; then
            echo "name=sdk" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/tags/proxy-v* ]]; then
            echo "name=proxy" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.7.1

      - name: Set node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: pnpm install
        working-directory: ./packages/${{ steps.package.outputs.name }}

      - name: Build
        run: pnpm build
        working-directory: ./packages/${{ steps.package.outputs.name }}

      - name: Publish
        run: pnpm publish --no-git-checks
        working-directory: ./packages/${{ steps.package.outputs.name }}
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
